x-docker_name: &DOCKER_NAME ""

services:
  *DOCKER_NAME:
    build:
      context: ./dockerfile
      dockerfile: Dockerfile
      shm_size: 32G
    volumes:
      - type: bind
        source: "./"
        target: "/python"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "127.0.0.1:6006:6006"
    tty: true
